type: 'swag'
update_interval: ???
max_cols: ???
activation: ???
layers:
  - type: 'Linear'
    in_features: 1
    out_features: 300
  - type: ${model.architecture.activation}
  - type: 'Linear'
    in_features: 300
    out_features: 1