# Bayesian Neural Network specific parameters
type: 'bnn'
layers:
  - {type: 'BayesLinear', prior_mu: 0, prior_sigma: 0.1, in_features: 1, out_features: 1000}
  - {type: 'ReLU'}
  - {type: 'BayesLinear', prior_mu: 0, prior_sigma: 0.1, in_features: 1000, out_features: 1}

