type: 'dropout'
dropout_prob: 0.4
layers:
  - {type: 'Linear', in_features: 1, out_features: 1000}
  - {type: 'ReLU'}
  - {type: 'MCDropoutLayer'}
  - {type: 'Linear', in_features: 1000, out_features: 1000}
  - {type: 'ReLU'}
  - {type: 'MCDropoutLayer'}
  - {type: 'Linear', in_features: 1000, out_features: 1}