defaults:
  - data: ???
  - model: ???
  - model/architecture: ???
  - plot: default
  - recorder: standard_wandb
  - train: ???


seed: ???

hydra:
  run:
    dir: ../output/hydra/training/${now:%Y-%m-%d}/${exp_name}
  sweep:
    dir: ../output/hydra/training/${now:%Y-%m-%d}
    subdir: ${exp_name}/${recorder.wandb.job_type}/seed_${seed}









